### ISSUE TITLE
feature_select not parsing batches correctly

### ISSUE THREAD

**Issue by ErinWeisbart** [cytomining/profiling-recipe#43]
Needs to be confirmed/replicated, but I had a config with two batches set up just like example in config:
```
---
batch: <FIRST BATCH NAME>
plates:
  - name: <FIRST PLATE NAME>
    process: true
  - name: <SECOND PLATE NAME>
    process: true
process: true
---
batch: <SECOND BATCH NAME>
plates:
  - name: <FIRST PLATE NAME>
    process: true
  - name: <SECOND PLATE NAME>
    process: true
process: true
```
and had all steps set to `perform: false` other than `feature_select`.

When I triggered it printed `Now processing...batch: Batch1` but went immediately to `Now processing...batch: Batch2` without performing the feature selection on Batch1. (Batch2 feature selected appropriately)

I then set Batch2 `process: false` and it errored:
```
  File "/Users/eweisbar/Desktop/github/PROJECT/profiling-recipe/profiles/utils.py", line 15, in load_pipeline
    if "pipeline" in data.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
```
I then deleted Batch2 from the config and Batch1 ran fine.
